//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TransactionIndex_4f1ef06c_d956_4805_8bfc_d1e9303426ce
    {
        public System.Guid Id { get; set; }
    }
}
