//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerAssign
    {
        public int TrainerAssignID { get; set; }
        public string TopicID { get; set; }
        public string TrainerID { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
