//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.TraineeAssigns = new HashSet<TraineeAssign>();
        }
    
        public string TraineeID { get; set; }
        public string TraineeName { get; set; }
        public string TraineeAddress { get; set; }
        public int TraineeAge { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MProgramL { get; set; }
        public int TOEIC { get; set; }
        public string Experience { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeAssign> TraineeAssigns { get; set; }
    }
}
