//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingStaff
    {
        public string TStaffID { get; set; }
        public string TStaffName { get; set; }
        public string TStaffAddress { get; set; }
        public int TStaffPhone { get; set; }
        public string TStaffEmail { get; set; }
    }
}
